<template lang="md">
  <div class="text-center">
    <img src="/la_place_publique_web_120.jpg" height="120" width="120">
  </div>
  <div class="text-justify my-5">
    <p>La situation politique et sociale de la France est à son niveau le plus bas. Les Français vivent dans un malaise constant. Le mouvement des gilets jaunes émergeant en novembre 2018 de la montée en force d’une incompréhension générale du peuple face à une dictature des marchés s’essouffle semaines après semaine. Pourtant, le malaise est toujours présent. Le peuple sans patrie se retrouve à la merci d’un prédateur invisible et de son bourreau, l’Union Européenne : entité atlantiste antidémocratique imposée aux nations.</p>
    <p>En Europe, le capitalisme libéral fait rage, détruisant les nations et forçant les peuples à migrer indéfiniment dans l’espoir d’un avenir meilleur. Le dollar-roi forcé par les États-Unis au début des années soixante-dix affaiblit un à un les États-Nations, favorisant la corruption comme jamais auparavant et poussant les pays à quémander des «aides financières» au Fonds Monétaire International (FMI) à des taux d’emprunts défavorables plongeant les peuples dans la dette sur plusieurs générations.</p>
    <p>La République Française, au coeur de la création de l’Union Européenne, se dirige peu à peu vers la construction d’une dictature. Les gouvernements successifs de la Vème République Française suppriment sournoisement les libertés d’expression et de mouvement des Français. La population est épuisée par des siècles de guerres meurtrières et autres génocides orchestrés sur sa terre tant qu’ailleurs. Pour accumuler toujours plus de richesses financières, les états complices des nations unies, produisent, polluent et pillent sans se soucier de l’impacte sur les générations futures. Les animaux, les plantes et autres ressources de notre planète sont consommés jusqu’à ce qu’il n’y en ait plus. C’est une histoire catastrophique qui s’écrie tant sur le plan humain que celui de son environnement. C’est à se demander si la république des droits de l’homme universels n’existe pas que pour nourrir une soif toujours plus avide de morts. Il fut un temps où les pères fondateurs de l’Union Européenne envisageaient une Europe constituée de nations indépendantes et non une Europe destructrice des nations vassale des marchés financiers.</p>
    <p>Certains penseurs français crient au «grand remplacement» pour parler des nouvelles vagues migratoires clandestines et incontrôlées imposées par l’Union Européenne. On peut comparer cette méthode de substitution des masses constituantes d’un pays avec celle employée en Amérique du Nord depuis plus de deux siècles où on constate que les populations autochtones américaines y sont presque aujourd’hui inexistantes. Quant à leurs terres, elles sont occupées par des gens d’origines diverses. Ce mélange ethnique créé à l’échelle nationale une nouvelle population stérile de toute histoire commune et par conséquent sans futur commun. George Orwell dans son ouvrage 1984, nous avait prévenu “Qui contrôle le passé contrôle l’avenir. Qui contrôle le présent contrôle le passé”. Aussi, contrairement aux messages véhiculés par les parangons de la bien-pensance ultra-libérale, auxquels se sont ajoutés les orphelins marxistes, l’immigration apporte plus de misère que de bien aux immigrés. Le traitement infligé aux immigrés africains en France reste toujours le même. Pour la plupart d’entre eux, ils vont se retrouver sans emplois, sans avenir et abandonnés dans des cités de la banlieue rouge parisienne, ou autres infrastructures similaires à Lyon ou à Marseille. Dans le meilleur des cas, leurs enfants intègreront le système malgré tout, en passant par une phase d’exploitation par les grandes entreprises qui abuseront de leurs besoins d’intégration. Dans le pire, ils seront attirés par le chant des sirènes de la délinquance locale et drainés vers l’exclusion sociale. Quant aux citoyens devant les recevoir, ils se retrouvent malgré eux à supporter financièrement et physiquement ce mouvement de populations prémédité. L’immigration sans sélection telle que pratiquée génère malheureusement plus d’exclus du système que de citoyens intégrés. Nous accusons les gouvernements successifs de la République Française d’avoir poussé des populations africaines à l’exode et abandonné ces dernières comme ils ont abandonné les Français.</p>
    <p>À force de matraquage médiatique quotidien et de la propagation de fausses informations, nous constatons que la population française a oublié les actions mal intentionnées des forces alliées durant la seconde guerre mondiale et après. 2019 marquant les soixante-quinze ans du débarquement des troupes alliées sur les côtes normandes, nous souhaitons rappeler entre autres les exactions commises par les forces alliées comme par exemple les bombardements sur des cibles civiles, les viols des Françaises et autres femmes européennes, la tentative échouée d’imposer un billet d’occupation placé sous le contrôle de Wall Street, et autres. La liste est longue. Néanmoins, des Français s’y sont opposés et ont su se réunir pour écrire une nouvelle constitution rétablissant pour un temps la souveraineté de la France sur son sol et à l’international. En 1971, la conférence de Bretton Woods imposa un système monétaire défavorable aux nations du monde qui placera le dollar US au coeur des échanges internationaux. En 1973, en France, l’application de la «loi Pompidou-Giscard» privatisa la Banque de France. Ce coup de poignard dans le dos du peuple français bénéficiera à la création de l’Euro, monnaie de singe, objet de ponction pécuniaire des populations passives européennes. Depuis la mise en place de l’Euro en 1999 et l’établissement de la Banque centrale européenne, l’Union Européenne, cette entité gouvernementale imposées aux peuples, se donne le droit de traiter les nations européennes comme des entreprises devant de dégager du profit. Ceci explique en partie la privatisation des biens communs tel l’aéroport de Paris par les favoris de l’Union Européenne, traîtres à leurs nations. L’Union Européenne n’a pas besoin de générer de profit grâce au bien commun des nations puisqu’il lui suffit de se servir directement et sans restriction dans la poche des citoyens européens abandonnés et divisés. Les citoyens trahis par leurs «élites» sont devenus le produit de consommation par excellence des banques internationales.</p>
    <p>La politique d’homogénéisation des nations menée par l’Union Européenne a pour conséquence : la chute de la natalité et l’exode des classes moyennes européennes. Ces facteurs alarmant ajoutés au mouvement contestataire populaires français des «gilets jaunes» en Europe indiquent une sérieuse dichotomie entre les peuples et leurs sphères dirigeantes.</p>
    <p>Pour pallier ce problème humain, nous pensons que la France doit écrire une nouvelle constitution dans laquelle le peuple participerait activement à la vie de la république. Une république respectueuse de ses citoyens et de leurs environnements. Nous prônons une lutte contre les régimes exclusifs qui bloquent l’ascension des hommes et des femmes capables de conduire la nation. Pour sa propre survie, il est impératif que les peuples s’opposent à l’avancée de l’Union Européenne. Cela passe par une réforme profonde de la France, de sa constitution, de sa politique et de son économie. Les Français de toutes origines doivent s’unir pour former un peuple et pouvoir devenir le moteur constituant de la patrie. La France doit devenir un modèle international capable de garantir la diversité et la cohabitation des nations.</p>
    <p>N’appartenant à aucune fraction ou caste politique, de nombreuses personnes trouveront difficile de positionner notre mouvement dans le spectre politique traditionnel. Notre but est de créer un mouvement capable de sauver les Français et les Françaises de cette folie orchestrée par le capitalisme libéral qui utilise forces militaires et systèmes de corruption pour détruire les pays et les piller de leurs ressources naturelles. Tel le ministère de l’Amour de 1984, le droit d’asile, les droits de l’homme, le devoir d’accueil ne sont que des prétextes pour les défenseurs d’une mondialisation à tout crin.</p>
    <p>Aujourd'hui, ce n'est plus une question de savoir si il faut faire une révolution ou non mais comment elle va se faire et comment l'après va se gérer. Nous devons devenir les acteurs de demain et arrêter de se laisser guider passivement vers un chaos certain.</p>
    <p>— <a href="https://t.me/yannicklescure" target="_blank" class="text-decoration-none">Yannick Lescure</a></p>
  </div>
</template>
